### ISSUE TITLE
Add Style Transfer Papers

### ISSUE THREAD

**Issue by TobiasLee** [THUNLP-MT/TG-Reading-List#1]
文本风格迁移也是近来非常火热的一个文本生成的话题，建议添加相关的文章。
可以参考 [文本风格转换 Paper List - 罗福莉](https://zhuanlan.zhihu.com/p/39211679)

**Comment by GrittyChen** [comment]
@TobiasLee 非常感谢您的建议，我们会尽快补上这部分相关论文列表。

**Comment by TobiasLee** [comment]
这是很棒的梳理工作，感谢整理~ 如果能够再搜集一下相关的 GitHub 代码也许能提供更大的帮助！

**Comment by GrittyChen** [comment]
@TobiasLee 嗯嗯，感谢提醒，希望能给对着方向感兴趣的人一些小的帮助！
